language: node_js
sudo: required
before_script:
  - npm install -g bower web-component-tester
  - bower install
env:
  global:
  - secure: I35STyVlx5sRKq29kE6rlPvz8ww65FTnH5vylbAO+gd7Qra2/yt3gUrOC/I7BqoRUwi0g83seMXTzkEqH38TpluK6Bxi/NSvNJcPpNPOUX7uWSZBGZKbYj5KhWmB3woCbbQeDiRjvsEBkzWExEhGstwE8j6vGYxSoVfm9e9jNkctLIVPl8bcusBjhL87I6xm69lBzAhTMgdw4lL13qWBcRzIikm6o5Z8ZdtBThmDJfgJ4aZegQHckm7r79gKfiU5hzlYR9zdeGerhBuUBh8qtETCSe5t5SUp+OVQDb2soF6ND6dTIiSDZTrMwMuXnl4ZaMFz0HwROgVQ5WVDt094n3xMRX+25REofaJ+NjyI0C8qTs3UDw9AA5uEEkaB2/zGDhE7VLuKN+H5OkHgaUveQjzGZnuZVmjs/gl/94hokobpYCCg1p++uovXyqf39R9v74KywJhK+t2tiOWWJCbcwTDCsF6PUJCsq5xama2pWJ5KKe6lg14H/kch6jiddqr8HWiiLVSDT6u/Es5OIfiR57HDm+71xZK6uwr3QnsPEGE/Gup/Ccx8X+pIO6YDa2wo6iSpe/FiBOnfCB3HWYLj1S7+MHiGe9hW+mStTKho1ANgi2MTgkvVqdSrYqgZQ4GEg+eYvuDNCVzIwWOMxKN3ZOM0qcSOaoQfLMlBU9oWQWM=
  - secure: dc4d23SFsFPOU6DUnoi9m+CzPeHHoKtuU328SlHAVXZetKb3awGUguzSgMO+bKCGL1FvPejCLLBeMYn+2oTg2LJKOB2tFRfJILX5MKyA/bQu7QY00kwxx3ne2J3I8oKb5+xlZ0KYjOFGMpIoKs1hrj19b6D8z9wsBfEnQyyuVCovT/mCjrBtbyuV2oY3FqX48lDse0gLql/WtM4GCiax507IvAuJ7kmepKg8YooarYfKU8EFmg3LSioeNGJQmTwlW0Pxa5/J+AF0dQ8gMVLmduRQosLuw/KEs+1swdH3Nu0GZ+YzeCnPO5V4uNciDYDyMOXDz0VrYFg/6K8iII7TakyxsQffO1TbP46aFQHjg5RkMWm65KFHGHy3CW50MuLFxYWl0tZo+hpzgMJjZVVUnxlUJ3bwvI5lrBnpn6kp2TvT0ukqICUgDQ26R38GLhX1vjBosH/obaK/OTUTVymidbOc11ibz7lt0HtR2EJ149dG6bgETSs9UKnlv1Yu+6+NLuOiTABCrMUBxeiwVp254cpTiB9iOmzdJj+d5IqdfrNt2AFS0mznV2XVCHiUvpXNgNLEKViC7Mhc34OrEqOcFpF/aJtkwkTKIJaHW0azzto4DItaW0itBNhacEtMpsBrOyBiGtUg8UvpnFCUg4/HPNsx3qh0rAJRz4UtBVLZqh0=
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run wct test/element && npm run test:server
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct test/element -s ''default''; fi'
dist: trusty
